version: '3'
services:
  dozer:
    build:
      context: ./seraph.pipeline
    hostname: dozer
    container_name: dozer
    environment:
      - "SERAPH_QUERY=REGISTER QUERY <people_to_be_tested> {FROM STREAM <test-dataset> STARTING FROM Earliest WITH WINDOW RANGE PT1M MATCH (p:Person)-[r:IS_WITH]->(p2:Person) RETURN p,r,p2; EMIT ON EXIT EVERY PT1M INTO <resulttopic>}"
      - "KAFKA_BROKER=broker:9093"
      - "NEO4J_BOLT=bolt://neo4j-sink:7687"
      - "NEO4J_USERNAME=neo4j"
      - "NEO4J_PASSWORD=sink"
      - "KAFKA_BROKER_CONNECTOR=broker:9093"
      - "KAFKA_CONNECT=connect:8083"
      - "NEO4J_HOSTNAME=neo4j-sink"
      - "FORCE_RESTART=true"
      - "KAFKA_CONNECT_NEO4J_BOLT=bolt://neo4j-sink:7687"

networks:
  default:
    external:
       name: dozer-network
